language: python
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - "export TEAMTEMP_SECRET_KEY=test_key"
  - "export DATABASE_URL=sqlite:///:memory"
script:
  coverage run manage.py test
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dc4e1369609d0c05dd0e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
